### ISSUE TITLE
Source code not available

### ISSUE THREAD

**Issue by Lemurhino** [TechGeekGamer/NX-LAN-PLAY-Launcher#1]
Need to see source code to trust. Especially because virustotal shows it as malware under two engines.

**Comment by BlackRabbit22** [comment]
https://www.virustotal.com/gui/file/3380179fdde93bd0f5bdd04d9a3d2f44124d3be4496b59665ce6f74f1a7affb7/detection

Here is the virus total scan. Shady and has no source code. Wouldn't recommend this being used.

**Comment by DanielC-08** [comment]
read Explaining Things.md

**Comment by DanielC-08** [comment]
I re-opened the issue since I am still trying to find out how to view the source code to my project.

**Comment by DanielC-08** [comment]
@BlackRabbit22 @Lemurhino I have source code and will post it within a few days. Ok?

**Comment by Lemurhino** [comment]
Perfect! Thank you for the effort, really appreciate it.

**Comment by TechGeekGamer** [comment]
I have given up on looking for a way to get source code. I am closing the project.
